---
- name: Create temporary bettercap build directory
  ansible.builtin.tempfile:
    state: directory
    suffix: build
  register: tempdir

- name: Build bettercap
  ansible.builtin.shell: |
    go env -w GO111MODULE=off
    go get -u github.com/bettercap/bettercap
  changed_when: false
  environment:
    GOPATH: "{{ tempdir.path }}"

- name: Install bettercap
  ansible.builtin.shell: |
    mv {{ tempdir.path }}/bin/bettercap /usr/local/bin/
    rm -rf {{ tempdir.path }}
    bettercap -version
  become: true
  register: output

- name: Display bettercap version
  ansible.builtin.debug:
    msg: "{{ output.stdout }}"
  when: output.rc == 0

# https://www.bettercap.org/usage/webui/
- name: Install bettercap caplets
  ansible.builtin.command: bettercap -eval "caplets.update; ui.update; q"
  when: output.rc == 0
  failed_when: false
  become: true
