---
- name: Set authorized keys taken from url
  ansible.posix.authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ github_username_keys }}"
  when: github_username_keys != ""

- name: Generate ssh key pair
  community.crypto.openssh_keypair:
    path: "{{ [user_home, '.ssh', 'id_rsa'] | path_join }}"
    force: false
    regenerate: never

- name: Install pypi packages
  ansible.builtin.pip:
    name: "{{ pip_pkgs }}"
    state: latest
    extra_args: "--no-cache-dir --upgrade"
    executable: pip3

- name: Create projects directory
  ansible.builtin.file:
    name: "{{ user_home }}/projects"
    state: directory
    mode: 0755

- name: Setup git repositories
  when: git_projects|length > 0
  block:
    - name: Clone git repositories
      ansible.builtin.git:
        repo: "{{ item.value }}"
        dest: "{{ user_home }}/projects/{{ item.key }}"
        force: false
      loop: "{{ lookup('dict', git_projects) }}"
      ignore_errors: true
      loop_control:
        label: "{{ item.key }}"

    - name: Generate vscode workspace file ~/projects/personal.code-workspace
      ansible.builtin.template:
        src: personal.code-workspace.j2
        dest: "{{ user_home }}/projects/personal.code-workspace"
        group: "{{ user_name }}"
        mode: 0640

- name: Import dotfiles tasks
  ansible.builtin.import_tasks: dotfiles.yml
  when: install_dotfiles
