---
- name: Set authorized keys taken from url
  ansible.posix.authorized_key:
    user: "{{ run_user }}"
    state: present
    key: "{{ github_username_keys }}"
  when: github_username_keys != ""

- name: Generate ssh key pair
  community.crypto.openssh_keypair:
    path: "{{ [ansible_env.HOME, '.ssh', 'id_rsa'] | path_join }}"
    force: no

- name: Install pypi packages
  ansible.builtin.pip:
    name: "{{ pypi }}"
    state: present
    executable: "pip3"

- name: Create projects directory
  ansible.builtin.file:
    name: "{{ user_home }}/projects"
    state: directory

- name: Cloning git repositories
  ansible.builtin.git:
    repo: "{{ item.value }}"
    dest: "{{ user_home }}/projects/{{ item.key }}"
  loop: "{{ lookup('dict', git_projects) }}"

- name: Run dotfiles install tasks
  ansible.builtin.import_tasks: dotfiles.yml
  when: install_dotfiles
