---
- name: Download get-docker.sh script
  ansible.builtin.get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: 0776

- name: Install docker
  ansible.builtin.command: /tmp/get-docker.sh
  environment:
    CHANNEL: stable

- name: Start docker daemon
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add user in docker group
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: docker
    append: true

- name: Reset ssh connection to apply user changes
  ansible.builtin.meta: reset_connection

- name: Create /etc/docker/daemon.json
  ansible.builtin.template:
    src: templates/docker_daemon.json.j2
    dest: /etc/docker/daemon.json
    group: docker
    mode: 0640

- name: Fetch docker-compose project github api json
  ansible.builtin.uri:
    url: https://api.github.com/repos/docker/compose/releases/latest
    return_content: true
  register: this

- name: Set docker-compose latest version
  ansible.builtin.set_fact:
    compose_version: "{{ this.content | from_json | json_query('tag_name') }}"

- name: Install latest docker-compose
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/{{ compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755

- name: Enable docker swarm mode
  community.docker.docker_swarm:
    state: present
    advertise_addr: "{{ docker_swarm_advertise_addr }}"
  register: output
  when: enable_docker_swarm_mode
