---
- name: Download docker install script
  get_url:
    url: "https://get.docker.com/"
    dest: "/tmp/get-docker.sh"
    mode: "0776"

- block:
  - name: Install docker
    shell: "/tmp/get-docker.sh"
    environment:
      CHANNEL: stable

  - name: Start docker daemon
    service:
      name: docker
      state: started
      enabled: true

  - name: Add user in docker group
    user:
      name: "{{ run_user }}"
      groups: docker
      append: true

  - name: Reset ssh connection to apply user changes
    meta: reset_connection

  - name: Create /etc/docker/daemon.json
    template:
      src: templates/docker_daemon.json.j2
      dest: /etc/docker/daemon.json

  - name: Enable docker swarm mode
    docker_swarm:
      state: present
      advertise_addr: "{{ docker_swarm_advertise_addr }}"
    register: output
    when: enable_docker_swarm_mode|bool == true

  become: yes