---
- name: Fetch homebrew version
  shell: brew --version
  register: output

- name: Display homebrew version
  debug:
    msg: "{{ output.stdout }}"

- name: Change ownership for `brew --prefix`
  shell: "chown -R {{ user_name }} $(brew --prefix)/*"
  become: yes

- name: Update Homebrew
  homebrew:
    update_homebrew: yes

- name: Upgrade homebrew core packages
  homebrew:
    upgrade_all: yes

- name: Upgrade homebrew cask packages
  homebrew_cask:
    upgrade_all: yes

- name: Install homebrew core packages
  homebrew:
    name: "{{ brew_pkgs }}"
    state: present

- name: Install homebrew cask packages
  homebrew_cask:
    name: "{{ brew_cask_apps }}"
    state: present
    install_options:
      - "appdir={{ brew_cask_appdir }}"
