---
- name: Fetch homebrew version
  ansible.builtin.command: brew --version
  register: output
  changed_when: false

- name: Display homebrew version
  ansible.builtin.debug:
    msg: "{{ output.stdout }}"

- name: Change ownership for `brew --prefix`
  ansible.builtin.command: "chown -R {{ user_name }} $(brew --prefix)/*"
  become: true

- name: Update Homebrew
  community.general.homebrew:
    update_homebrew: true

- name: Upgrade homebrew core packages
  community.general.homebrew:
    upgrade_all: true

- name: Upgrade homebrew cask packages
  community.general.homebrew_cask:
    upgrade_all: true

- name: Install homebrew core packages
  community.general.homebrew:
    name: "{{ brew_pkgs }}"
    state: present

- name: Install homebrew cask packages
  community.general.homebrew_cask:
    name: "{{ brew_cask_apps }}"
    state: present
    install_options:
      - "appdir={{ brew_cask_appdir }}"
