---
- name: Run update
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  become: true

- name: Install necessary packages
  ansible.builtin.apt:
    name: "{{ pkgs }}"
    state: latest
    update_cache: true
    install_recommends: false
    force_apt_get: true
  become: true

- name: Install snap packages
  community.general.snap:
    name: "{{ snaps }}"
    classic: true
  become: true

- block:
    - name: Check docker installed
      ansible.builtin.command: docker --version
      register: output
      changed_when: false
    - ansible.builtin.debug:
        msg: "{{ output.stdout }}"
  rescue:
    - name: Install and configure docker
      include_tasks: docker.yml

- block:
    - name: Check bettercap installed
      ansible.builtin.command: bettercap --version
      register: output
      changed_when: false
    - ansible.builtin.debug:
        msg: "{{ output.stdout }}"
  rescue:
    - name: Install bettercap
      include_tasks: bettercap.yml

- name: Check Nvidia card present
  ansible.builtin.command: lspci | grep -i --color 'vga\|3d\|2d' | grep -i NVIDIA
  register: output
  changed_when: false
  ignore_errors: true

- block:
    - ansible.builtin.debug:
        msg: "{{ output.stdout }}"

    - name: Download custom script
      ansible.builtin.get_url:
        url: "{{ gpu_utils_script }}"
        dest: /tmp/gpu_utils_script.sh
        mode: 0775

    - name: Install nvidia drivers, hashcat and aircrack-ng
      shell: /tmp/gpu_utils_script.sh
      become: true
  when: output.rc == 0
