---
- name: Run update
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  become: true

- name: Install packages
  ansible.builtin.apt:
    name: "{{ cli.pkgs }}"
    state: latest
    update_cache: true
    install_recommends: false
    force_apt_get: true
  become: true

- name: Install snap packages
  community.general.snap:
    name: "{{ cli.snap_pkgs }}"
    classic: true
  become: true

- name: Gather the package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Install and configure docker
  ansible.builtin.include_tasks: docker.yml
  become: yes
  when: "'docker-ce-cli' not in ansible_facts.packages"

- name: Bettercap block
  when: install_bettercap
  block:
    - name: Check bettercap installed
      ansible.builtin.command: bettercap --version
      register: output
      changed_when: false

    - name: Display bettercap version
      ansible.builtin.debug:
        msg: "{{ output.stdout }}"
  rescue:
    - name: Install bettercap
      ansible.builtin.include_tasks: bettercap.yml

- name: Check nvidia pci
  ansible.builtin.command: lspci | grep -i --color 'vga\|3d\|2d' | grep -i NVIDIA
  register: output
  changed_when: false
  ignore_errors: true

- name: Install nvidia drivers block
  when: output.rc == 0
  block:
    - name: Display nvidia pci output
      ansible.builtin.debug:
        msg: "{{ output.stdout }}"

    - name: Download custom script
      ansible.builtin.get_url:
        url: "{{ gpu_utils_script }}"
        dest: /tmp/gpu_utils_script.sh
        mode: 0775

    - name: Install nvidia drivers, hashcat and aircrack-ng
      ansible.builtin.command: /tmp/gpu_utils_script.sh
      become: true
