---
- name: Fetch package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Merge packages list
  set_facts:
    ppas: "{{ cli.ppas }}"
    ppa_keys: "{{ cli.ppa_keys }}"
    pkgs: "{{ cli.pkgs }}"
  when: "'ubuntu-desktop' in ansible_facts.packages"

- name: Add ppa
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: no
  with_items: "{{ cli.ppas }}"
  when: cli.ppas
  become: true

- name: Add ppa repo keys
  apt_key:
    url: "{{ item }}"
    state: present
  with_items: "{{ cli.ppa_keys }}"
  when: cli.ppa_keys
  become: true

- name: Install protonvpn deb package
  apt:
    deb: "{{ protonvpn_deb_pkg_link }}"
  become: true

- name: Run update
  ansible.builtin.apt:
    upgrade: true
    update_cache: true
  become: true

- name: Install packages
  ansible.builtin.apt:
    name: "{{ cli.pkgs }}"
    state: latest
    update_cache: true
    install_recommends: false
    force_apt_get: true
  become: true

- name: Install snap packages
  community.general.snap:
    name: "{{ item.key }}"
    classic: "{{ item.value.classic }}"
  loop: "{{ lookup('dict', cli.snap_pkgs) }}"
  loop_control:
    label: "{{ item.key }}"
  become: true

- name: Include docker tasks
  ansible.builtin.include_tasks: docker.yml
  vars:
    ansible_become: true
  when: "'docker-ce-cli' not in ansible_facts.packages"

- name: Bettercap block
  when: install_bettercap
  block:
    - name: Check bettercap installed
      ansible.builtin.command: bettercap --version
      register: output
      changed_when: false

    - name: Display bettercap version
      ansible.builtin.debug:
        msg: "{{ output.stdout }}"
  rescue:
    - name: Include bettercap tasks
      ansible.builtin.include_tasks: bettercap.yml

- name: Check nvidia pci
  ansible.builtin.shell: |
    lspci | grep -i --color 'vga\|3d\|2d' | grep -i NVIDIA > /dev/null 2>&1
  register: output
  changed_when: false
  ignore_errors: true

- name: Install nvidia drivers block
  when: output.rc == 0
  block:
    - name: Display nvidia pci output
      ansible.builtin.debug:
        msg: "{{ output.stdout }}"

    - name: Include gpu utils tasks
      ansible.builtin.include_tasks: gpu-utils.yml
      vars:
        ansible_become: true

  - name: Change ubuntu gnome app icon location
    ansible.builtin.command: "gsettings set org.gnome.shell.extensions.dash-to-dock show-apps-at-top true"
    when: "'ubuntu-desktop' in ansible_facts.packages"
