---
- name: Run update
  apt:
    upgrade: true
    update_cache: yes
  ignore_errors: yes
  become: yes

- name: Install necessary packages
  apt:
    name: "{{ pkgs }}"
    state: latest
    update_cache: yes
    install_recommends: no
    force_apt_get: yes
  become: true

- name: Install snap packages
  snap:
    name: "{{ snaps }}"
    classic: yes
  become: true

- block:
  - name: Check docker installed
    shell: docker --version
    register: output
  - debug:
      msg: "{{ output.stdout }}"
  rescue:
  - name: Install and configure docker
    include_tasks: docker.yml

- block:
  - name: Check bettercap installed
    shell: bettercap --version
    register: output
  - debug:
      msg: "{{ output.stdout }}"
  rescue:
  - name: Install bettercap
    include_tasks: bettercap.yml

- name: Check Nvidia card present
  shell: lspci | grep -i --color 'vga\|3d\|2d' | grep -i NVIDIA
  register: output
  ignore_errors: true

- block:
    - debug: msg="{{ output.stdout }}"

    - name: Download custom script
      get_url:
        url: "{{ gpu_utils_script }}"
        dest: /tmp/gpu_utils_script.sh
        mode: 0775

    - name: Install nvidia drivers, hashcat and aircrack-ng
      shell: /tmp/gpu_utils_script.sh
      become: true
  when: output.rc == 0
